    teleop_twist_joy_node:
      ros__parameters:
        axis_linear:  # Mặc định là linear.x
          x: 1        
        scale_linear:
          x: 0.12      # Giảm xuống từ 0.8671 để phù hợp với giới hạn 0.5 m/s trong control.yaml
        scale_linear_turbo:
          x: 0.12     # Giảm xuống từ 0.8671 để phù hợp với giới hạn 0.5 m/s trong control.yaml
                        # (Hoặc đặt thấp hơn nếu muốn chế độ turbo chậm hơn max)
        axis_angular:
          yaw: 0      # Giữ nguyên
        scale_angular:
          yaw: 0.4    # GIẢM để phù hợp với giới hạn 0.4 rad/s mới (0.6 -> 0.4)
        scale_angular_turbo:
          yaw: 0.4    # GIẢM để phù hợp với giới hạn 0.4 rad/s mới (0.6 -> 0.4)

        # Thêm deadzone để tránh lệnh không mong muốn từ joystick
        deadzone_linear:
          x: 0.05     # Thêm deadzone để tránh các lệnh nhỏ không mong muốn
        deadzone_angular:
          yaw: 0.05   # Thêm deadzone để tránh các lệnh nhỏ không mong muốn

        enable_button: -1          # Nút L1 (Shoulder Left) làm deadman switch (cần giữ để di chuyển)
                                  # Nếu không muốn deadman, đặt là -1 hoặc bỏ dòng này
                                  # và đảm bảo `require_enable_button` là false (mặc định là true)
        require_enable_button: false
        # enable_turbo_button: 5  # Nút R1 (Shoulder Right) để kích hoạt turbo
        
        # Invert axes if necessary (PS4 controller often needs this)
        # invert_linear_x: true
        # invert_angular_yaw: true 
        
        # Nếu bạn muốn sử dụng các nút khác hoặc các trục khác, bạn cần tìm ra chỉ số của chúng.
        # Một cách là echo topic /joy khi joy_node đang chạy và di chuyển/nhấn các nút.
        # sensor_msgs/msg/Joy có hai mảng: axes và buttons. Chỉ số trong mảng đó là thứ bạn cần.
        # Thêm tham số mới
        scale_linear_exponent: 1.5  # Tạo đáp ứng phi tuyến
        
        # Đảo trục nếu cần thiết cho tay cầm PS4
        invert_linear_x: true       # Đảo chiều (đẩy lên = tiến)
        
        # Giảm giới hạn tốc độ thay đổi để tránh quá tải buffer
        rate_limit_linear_x: 0.3   # Giảm xuống để tránh buffer đầy
        rate_limit_angular_z: 0.3  # Giảm xuống để tránh buffer đầy
        
        # Thêm tham số publish frequency
        publish_frequency: 20.0    # Giảm tần số từ mặc định (50Hz) để tránh quá tải MCU